### ISSUE TITLE
First day of the week

### ISSUE THREAD

**Issue by BugsOli** [rwilson504/PCFControls#121]
Hello, and thanks for this awesome control!
It would be nice to choose the first day of the week in the calendar instead of defaulting to Sunday.

For example through a parameter in the control settings or by reading the user's settings in D365.

Thanks

**Comment by rwilson504** [comment]
This has actually been a requirement from a few other people too.  I'm going to work on it this week along with allowing you to select which days you would like to exclude from the work week view.

**Comment by ArtKarp** [comment]
> 
> 
> Hello, and thanks for this awesome control!
> It would be nice to choose the first day of the week in the calendar instead of defaulting to Sunday.
> 
> For example through a parameter in the control settings or by reading the user's settings in D365.
> 
> Thanks

What D365 user setting would tell you that Monday is the starting day of the work week for a user?   Under personalization settings I only see Default Calendar and Start/End time.  Have I missed something?

Using language, like "en", doesn't work.  It applies to US, UK, AU, and Canada. US and Canada start on Sunday and UK and AU start on Monday. All of the countries use "en" in D365.

If the language is anything other than "en", you could assume to start on Monday instead of Sunday.

**Comment by BugsOli** [comment]
You are 100% correct mate! I was in Outlook at the time of writing and didn't pay attention 🤣
