### ISSUE TITLE
Some feedback for Model Driven case

### ISSUE THREAD

**Issue by forceworks** [rwilson504/PCFControls#126]
It would be great if we could bind to existing fields, where possible, instead of entering the field name as a string which could change

**Comment by ArtKarp** [comment]
Doesn't the logical name work?     For example, using the Account name:   "name" vs "Account Name".  The logical name is all lowercase "name" vs the string 'Account Name'.   This is an issue in canvas app design.  If you don't use the logical name and someone changes the text it will cause an issue.  While the app will work, if you open it in the designer it throws an error.  Then auto-save kicks in and you are screwed.  Red underlines all over your screen and you have no clue as to why or how to fix it. 😱

**Comment by forceworks** [comment]
Feedback from someone who does not care about canvas 😊

Thanks!

Steve Mordue MVP
813-263-7129

**Comment by rwilson504** [comment]
Steve,

I chose to use the logical name inputs for the fields for a few reason.  One of which Art mentioned is that things in Canvas break less when you use the logical name rather than the display name.  My secondary reason though was to allow you to pull data from related entities.  For instance if you want to use something other than the primary attribute as the display name for a resource or event you can do that with my control, eg: raw_entityname.raw_attributename.  Utilizing the field picker you cannot select fields from related entities.  Finally logical names don't change when you update the display name of a field so I though it would actually be more stable to utilize that method.

Thanks,

Rick
