### ISSUE TITLE
Possibility to hide command bar?

### ISSUE THREAD

**Issue by urossavelj** [rwilson504/PCFControls#130]
Would it be possible to hide the command bar of the subgrid?

**Comment by rwilson504** [comment]
@urossavelj You can hide the command bar but unfortunately not based upon the grid being a regular one vs a subgrid.  The visibility options for the Command Bar, View Selector, and Quick Search are in the ControlManifest.Input.xml file.  The data-set node has an attribute called cds-data-set-options, this is where you can set the visibility of these items.

`<data-set name="sampleDataSet" display-name-key="Dataset_Display_Key" cds-data-set-options="displayCommandBar:true;displayViewSelector:true;displayQuickFindSearch:true">
  `

Because the ControlManifest.Input.xml options are set during the building of the component there is no way to change them at run time.  Yes there are unsupported ways of hiding these components using javascript but i try to stay away from those whenever possible.  My suggestions would be to build the source yourself into a component you use specifically for subgrids which hide that feature.

**Comment by urossavelj** [comment]
Thanks for the information!
