### ISSUE TITLE
Pin Clustering

### ISSUE THREAD

**Issue by en4cer** [rwilson504/PCFControls#132]
Would it be possible to add pin clustering to this control?

**Comment by rwilson504** [comment]
@en4cer, Thanks for the suggestion.  I have updated the control to have clustering now.  Additionally i added some code to reduce the number of time the calendar will attempt to load the data which should speed it up a bit.  I added a few properties to the controls. 

Clustering Enabled (Text) - Set to true or false
Clustering Placement (Enum) - Mean Average or First Location [See Definitions](https://docs.microsoft.com/en-us/bingmaps/v8-web-control/modules/clustering-module/clusterplacementtype-enumeration)
Cluster Grid Size (Number) - The width and height of the gird cells used for clustering in pixels
Cluster Pushpin Color - Set the color to a hex value to distinguish the difference between a cluster pin and a regular pin.  If you don't set it the default with be the default pin color.

**Important Note** - Be aware that because new properties were added to the PCF component you will need to complete the following for each view containing this component.  If you do not complete these steps your view may no longer load.

- Open each view containing this component
- Click on Custom Controls link on left
- Click on the component name
- Update the properties if you want
- Click the OK button
- Save the view
- Publish the view

![image](https://user-images.githubusercontent.com/7444929/108638235-3cc09780-745c-11eb-9616-b78b19a05c0f.png)

Here is an example using a large data set.

![image](https://user-images.githubusercontent.com/7444929/108638190-f703cf00-745b-11eb-8bd8-88817f376215.png)
