### ISSUE TITLE
Model base calendar Date-Picker mode?

### ISSUE THREAD

**Issue by wendellsimmons** [rwilson504/PCFControls#154]
I have a use case where a subgrid embedded calendar is used as a "Date-Picker" by clicking on the displayed event entries which fires an OnSelect/OnClick event passing the event record's ID in the model app.

If this behavior is available in the canvas app version, I could embed the canvas app version, but how it might possible was not obvious to me.

Thx

**Comment by rwilson504** [comment]
Yes you can utilize the output parameters of the control in the canvas app.  I have provided the ability to capture the click on an event as well as the click on empty area so that you could create a new event for that time span.

Below is an example of the two methods.

![2021-04-16_9-14-36](https://user-images.githubusercontent.com/7444929/115029783-55659080-9e94-11eb-97fb-128883810c64.gif)

In order to make it work you can utilize the OnChange event of the Calendar Control.  Here is a screenshot of the event highlighting how to utilize the output parameters to set variables in your canvas app that will allow you to utilize the data.

![image](https://user-images.githubusercontent.com/7444929/115029805-5b5b7180-9e94-11eb-83b6-1442e0a00ff7.png)

```
//This provides the ability to act upon actions from the react components 
//such as a record being click on or an empty time slot being selected
If(
    CalendarControl.actionRecordSelected,
    Set(SelectedRecordID, CalendarControl.selectedRecordId);
    //Navigate(OpenExistingEvent);,
    Set(CloseRecordContainer, true);,    
    CalendarControl.actionSlotSelected,
    Set(SelectedSlotStart, CalendarControl.selectedSlotStart);
    Set(SelectedSlotEnd, CalendarControl.selectedSlotEnd);
    Navigate('New Event'); 
);
```

**Comment by wendellsimmons** [comment]
Rick,

Thanks for the quick response and detailed information. I'll give it a go.

Cheers,
Wendell Simmons | kcvisual.media | +1.510.919.0517 (call/text)

**Comment by wendellsimmons** [comment]
Hi Rick,

Thanks for the help. I had successfully deployed the model calendar but
based on your response I need to embed a canvas app calendar instead so I
can get the selected event guid.

I've set up a canvas app with the calendar control and am attempting to
link the OOB Appointments entity like this:

Screen1: OnVisible:  ClearCollect(calendarEvents, Appointments);

The calendar control is: calendarEvents

The calendarEvents properties are:
[image: image.png]

Do you see what I missed?

Cheers,
Wendell Simmons | kcvisual.media | +1.510.919.0517 (call/text)

**Comment by rwilson504** [comment]
Wendell,

Looks like the image of your properties didn't come through, can you try sharing it again.

Thanks,

Rick

**Comment by wendellsimmons** [comment]
Rick,

Here is the screen control
[image: image.png]

Here is the calendar control
[image: image.png]
Wendell Simmons | kcvisual.media | +1.510.919.0517 (call/text)

**Comment by rwilson504** [comment]
Wendell,

Sorry your images are still not coming through on the git comments.  Here is what it looks like.

![image](https://user-images.githubusercontent.com/7444929/115396869-77705300-a1b3-11eb-9918-bae2da6b3f67.png)

Also did you know you can now just copy/paste or drag an image directly into git comments.  It will do an auto upload of the images.  https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests

**Comment by wendellsimmons** [comment]
Maybe third time is the charm..
![screen](https://user-images.githubusercontent.com/73668530/115417338-274abe00-a1be-11eb-8b40-2cf819e436a1.JPG)
![calendar](https://user-images.githubusercontent.com/73668530/115417361-2b76db80-a1be-11eb-8f8e-84809e7f7ce4.JPG)

**Comment by rwilson504** [comment]
Third time was a charm!  Ok so i think i got it figured out.  This is happening because of a new Preview Feature called **Explicit column selection**.  It was created so that apps would load faster by only returning the data it needs.  Because the calendar control does not specify specific fields in the way a gallery does the data is not returned when this feature is turned on.  Here are the options to fix it.

Option 1: Turn off the Explicit column selection.  Go to the settings area of your app and turn it off.  Make sure to save the app after you turn this off then close the app completely in the studio and re-open, otherwise you won't see the results of the change.

![image](https://user-images.githubusercontent.com/7444929/115441740-32faac80-a1df-11eb-90fe-5337de3bc1c3.png)


Options 2: When you build out your collection specify the columns you want using the ShowColumns function.
![image](https://user-images.githubusercontent.com/7444929/115441827-4dcd2100-a1df-11eb-953b-cce95d49d2cf.png)

**Comment by wendellsimmons** [comment]
Hey Rick, that worked great. I'm getting the appointment GUID now using
your example and can display the GUID in a Label. Woohoo!

As you see I also attempted to grab the Subject/title, but nothing is
returned into a mapped  text label. No error is given.

If(
    Calendar1.actionRecordSelected,
    Set(SelectedRecordID, Calendar1.selectedRecordId);
    Set(Title,Calendar1.Selected.subject)
   )


Wendell Simmons | kcvisual.media | +1.510.919.0517 (call/text)

**Comment by wendellsimmons** [comment]
I got it working, thanks!
Wendell Simmons | kcvisual.media | +1.510.919.0517 (call/text)

**Comment by wendellsimmons** [comment]
Hi Rick, this is the last question:  I want to patch the selected
appointment record the user selected on the calendar back into the
Appointment lookup on the parent record. I can't figure out the patch
syntax from everything I've found online.

Patch(Scheduling,ModelDrivenFormIntegration.Item,{Appointment:LookUp(Appointments,Appointment
= SelectedRecordID})


Wendell Simmons | kcvisual.media | +1.510.919.0517 (call/text)
