### ISSUE TITLE
[BUG] [Calendar] Limit on the number of items calendar can handle?

### ISSUE THREAD

**Issue by Craig-Humphrey** [rwilson504/PCFControls#321]
**Which PCF Component**
Calendar

**What type of Power App are you using this PCF component in?**
 - Canvas App

**Describe the bug**
There seems to be a limit on how many items the calendar can handle.
I'm currently working in the day view and see two symptoms:
1. I used FirstN to slowly increment how many items in the underlying collection. Once I get over 54 items, but only the first 54 are displaying.
2. If my first attempt to populate the collection is with more than this, then the calendar remains blank.

**To Reproduce**
1. Add calendar control to screen, wire up properties
2. Save, Close and re-open app
3. Populate collection (that is linked to the calendar items) with more than 54 items

**Expected behavior**
I know this is a lot of items, particularly for a single day, but that's a different conversation with the client.
I'd like it to display all the items.  It doesn't need to be unlimited, but probably needs to be nearer 100 for a single day/single resource and then 1000s for multiple resources.

**Screenshots**
N/A

**Additional context**
While this is possibly a bit of a bug, I'm also going to have to have the conversation with the client around the practicality of having so many items in a calendar, as the readability goes out the window... And it's only going to get worse on a multi-resource view.

**Comment by Craig-Humphrey** [comment]
OK, perhaps this isn't the specific bug.

I was managing to reproduce this time and time again, but now it's working...

Perhaps it's related to a different issue/bug I'm experiencing.

I have two icons that interact with the collection that is behind the calendar.
1. Resets the collection back to the source data.
2. Adds "white space" entries - the gaps between calendar items - into the collection.

However, I'm finding that I have to click the second icon twice, before it has an impact on the calendar, even though I know it's updating the collection involved.

Any ideas?

**Comment by Craig-Humphrey** [comment]
And possibly related - the calendar only updates when there are click/select events from the mouse.
The calendar doesn't refresh if I update the collection in a Screen.OnVisible or Select(Control).
Even when I update the collection before a navigation - it doesn't pick up the changed collection.

I feel like I'm missing something intrinsic here....

**Comment by rwilson504** [comment]
The behavior you're encountering stems from some intrinsic limitations of PCF controls in Power Apps, such as the absence of a `Reset` function. However, the method I've outlined not only addresses this limitation but also provides a way to update the calendar control whenever needed, giving you greater flexibility.  The Sample app I provided also includes the following:

### Solution: Use a Toggle to Control Data Reload

Instead of relying solely on `Screen.OnVisible` or `Select(Control)` for updating the calendar, this method leverages a toggle control to manage data updates. Here's how you can implement it:

#### 1. Add a Toggle Control
- Place a **Toggle** control on the form with the calendar.
- Set its `Default` property to a variable, e.g., `LoadDataIsChecked`.

#### 2. Configure the Toggle's Behavior
Set the following properties for the toggle:

**`OnCheck`:**
```powerapps
// Load or refresh the calendar's data source
ClearCollect(calendarEvents, 
    SortByColumns(
        AddColumns(
            Filter(Events, Start <= CalendarRangeEnd && End >= CalendarRangeStart && Status = 'Status (Events)'.Active), 
            eventcolor, Resource.Color,
            resourceId, Resource.Resource,
            resourceName, Resource.Name
        ), 
        "resourceName", SortOrder.Descending
    )
);

// Reset the toggle state
Set(LoadDataIsChecked, false);
```

**`OnUncheck`:**
```powerapps
false
```

#### 3. Update `Screen.OnVisible`
In the `OnVisible` property of the screen with the calendar, add:
```powerapps
Set(LoadDataIsChecked, true);
```

This ensures the toggle's `OnCheck` logic is triggered whenever the screen is loaded.

#### 4. Enable Manual Updates
To refresh the calendar data manually (e.g., via a button), simply set the variable:
```powerapps
Set(LoadDataIsChecked, true);
```

### Key Benefits of This Approach
1. **PCF Limitation Workaround:** Since PCF components lack a `Reset` function, this method provides an effective way to reset or update the control indirectly.
2. **Flexibility:** By using a toggle, you can trigger updates at any time, not just during screen navigation.
3. **Control Over Data Refresh:** The logic ensures that the calendar control always reflects the latest data without relying solely on `Screen.OnVisible`.

This method is not about avoiding a dependency on `Screen.OnVisible`, but rather enhancing functionality by overcoming the inherent limitations of canvas apps and PCF components.
