### ISSUE TITLE
Control Picker Solution?

### ISSUE THREAD

**Issue by ArtKarp** [rwilson504/PCFControls#36]
On the released files download page, there is a solution file named "controlpicker".  Is that the Color Picker?

**Comment by rwilson504** [comment]
Yes that is the color picker.  That was the first control i ever wrote and I didn't pay too much attention to the solution name.  I'll update the build script to show the correct zip file name but I'm going to leave the solution name the same since I know some people are currently using it and i don't want to break there future imports.
