### ISSUE TITLE
No Component

### ISSUE THREAD

**Issue by forceworks** [rwilson504/PCFControls#52]
Hi Rick, trying out the calendar control. Installed managed solution, but no control visible :(

**Comment by ArtKarp** [comment]
Hi Steve,

If you are trying to add the control in a canvas app:
 
1. After installing the solution file, make sure that code components is enabled for the org you are using, 
2. Open the canvas app, navigate to components > Import > Code > Calendar

3. To add it to the screen, you need to click the "+ Insert" button on the left nav bar

4. Navigate and expand "Code components" and select Calendar 
(Note: Code components, for me, are not shown under the usual top menu bar "Custom" where I would expect them to be.  Could be by design or a bug.)

Overall I have found this is a really great calendar control for Canvas apps. 

I haven't worked with using the control in a model app yet. So I can't help you there. 

Hope this helps,
-Art

![image](https://user-images.githubusercontent.com/25698082/82082828-88f4d500-969d-11ea-86a9-e8cf21a1b4fc.png)

**Comment by forceworks** [comment]
Ah. That’s it, I was trying to use it in Model

Thanks!

Steve Mordue MVP
813-263-7129

**Comment by ArtKarp** [comment]
I do know that in a model app, you have to create an entity view, and add the control to the view and indicate the fields used for event name, start date, end date.   

The control is view specific and can't be added at the entity level as a control that applies to all views as you can do with the Dynamics calendar control. 

-Art

PS. I have a long list of issues I would be happy to add to your list on needed AppSource fixes  :)

**Comment by forceworks** [comment]
Yes, it does not show up in the list of controls for views like the other controls do, not sure why

Steve Mordue
Forceworks Global
Via Mobile
813-263-7129
________________________________

**Comment by rwilson504** [comment]
Steve,

Can you provide some screenshots of what how you are attempting to add the control in a Model app?  I'm able to see the control there and have it working.

![image](https://user-images.githubusercontent.com/7444929/83923671-b985d700-a750-11ea-82e6-3f7c17e27e54.png)

**Comment by hitendra72** [comment]
I've successfully imported the Calendar PCF using the managed solution from Github, and am able to insert it into my canvas app.

However, I'm not sure what I'm doing wrong to get the calendar to show events

My scenario:
1. I have a CDS entity called "myevents" created with fields "event", "start" & "end"
2. The unique identifier for this entity is "hc_myeventsid".
2. Data from this entity is loaded into a collection (colAppt) in the canvas app (in AppStart), as recommended in the readme.
3. in the PCF control, I have put "hc_myeventsid" (with the double quotes) in the eventid field.
4. In the field calendarDataSet_Items, I have put the collection as the source.
5. No fields have been selected under Properties for the control.

But the calendar is not showing the events.

Putting just hc_myeventsid (without the double quotes) throws an error

When the app is saved, exited and restarted, the Default field is populated with a "ThisItem.hc_myeventsid", which throws a formula error

What am I missing?

**Comment by rwilson504** [comment]
In the calendar properties did you fill in the name of the Name, Start, End Fields?

![image](https://user-images.githubusercontent.com/7444929/85159504-987eb500-b22b-11ea-865f-59c85b37e0c2.png)

Also instead of building out my collection in the App Start I have moved to doing it into a toggle which allows me to run functionality on the onCheck and onUnCheck.

![image](https://user-images.githubusercontent.com/7444929/85159993-42f6d800-b22c-11ea-9587-5db535b9e3ab.png)

**Comment by rwilson504** [comment]
Also I just uploaded a sample managed solution you can install. 

This sample does not include the Calendar component in it so that you can easily install/remove this managed solution without accidentally removing the Calendar component from your system.  

There is a model app included with the solution so you can easily add/modify data and it also includes a Canvas app where i have provided different ways you can utilize the calendar.

https://github.com/rwilson504/PCFControls/blob/master/Calendar/Sample/CanvasCalendar_1_0_0_1_managed.zip

Let me know what you think.

Thanks,

Rick

**Comment by hitendra72** [comment]
Thanks Rick - much appreciated

The import of the managed solution fails, as it requires a custom control which I don't have (screenshot below)

![image](https://user-images.githubusercontent.com/46102183/85195636-c7b62480-b306-11ea-8dcb-075e8f25e49d.png)

But I just configured the React Calendar again from scratch with a custom entity which had the relevant fields, and it works.

However, when I changed to using the standard Appointments entity in CDS, the control doesn't seem to work.

My settings when using the standard Appointments entity are:
eventFieldEnd: "scheduledend" 
eventFieldName: "subject"
eventFieldStart: "scheduledstart"
eventId: "activityid"

I suspect this is because Appointments uses the activityid as it's GUID, which is really just a pointer.
Is this something you have faced as well?

**Comment by rwilson504** [comment]
Yes i have found that attaching directly to a CDS entity usually doesn't work.  I would always suggest using a collection.

Also here is an updated Sample that does not include the Scheduler component.

https://github.com/rwilson504/PCFControls/blob/master/Calendar/Sample/CanvasCalendar_1_0_0_3_managed.zip
