### ISSUE TITLE
Capitalize "All" day?

### ISSUE THREAD

**Issue by ArtKarp** [rwilson504/PCFControls#66]
Just a suggestion for the Agenda view.

![image](https://user-images.githubusercontent.com/25698082/82743177-74a77c80-9d1c-11ea-87a5-e817f923b52c.png)

**Comment by ArtKarp** [comment]
Now that I am testing the other languages, this text expands in the time column.  

Also the "all day" time column header cuts off Spanish, Dutch and Russian languages, 


![image](https://user-images.githubusercontent.com/25698082/82855919-87a78180-9ec1-11ea-8f9e-05fda1ba6c4a.png)

**Comment by rwilson504** [comment]
I'm going to make the All Day on the agenda show in the case in which the label defines it.  

As far as the All Day text on the day view I'm going to shrink the text to 12px and push the padding over so it at least won't bump into the rest of the header.  I'm also going to add a title to the span so that if you hover over the text when it's cut off with ellipses it will show you the full text in the hover.

![image](https://user-images.githubusercontent.com/7444929/83920687-c0115000-a74a-11ea-9d3a-2c1a9e3b4149.png)
