### ISSUE TITLE
Expected Record Value

### ISSUE THREAD

**Issue by ArtKarp** [rwilson504/PCFControls#70]
I copied via solution the test calendar I have been developing into a new environment.  Now when I run it I get an error of "expected record value" and the calendar is blank.  When I look at the collections, all the records expected have been created.  This is the app I have shown you and haven't had any problems with. 

I created a new app, installed calendar control and copied the code from the original test app to the new one without making any changes. The collections are created and data is displayed as expected. 

Any ideas as to what might break an existing app with the control? 

![image](https://user-images.githubusercontent.com/25698082/83811080-fe850d00-a66d-11ea-9cb6-27e4c6714c1a.png)

**Comment by rwilson504** [comment]
I just got the same error.  Was working just fine last night but this morning I'm getting an error.  I'll take a look.

**Comment by rwilson504** [comment]
This looks as though it's a breaking change due to something MS did in their recent release. As soon as I opened up my app in the editor I had the same issues.  After saving it I went back and looked at all the versions and it appears that the upgrade to Power Apps 3.20053.24 must have introduced some sort of breaking change.  As soon as I put an older version using Power App 3.20051.16 it worked just fine again in the player.

![image](https://user-images.githubusercontent.com/7444929/83877500-a3ecbf00-a708-11ea-8bbd-5e6d29127a66.png)

A couple of things to note.
-The app did not actually break until i opened the editor which then updated the Power Apps version of the app.
-I did some testing and was actually able to get it working again in the same app without having to create a whole new app and copying over all my code.
 * Open the existing app in the editor.
 * Copy the properties you have in the Calendar component 
 * Remove the Calendar component from the App.
 * Save and Publish the App.
 * Re-open the App in the Editor and re-Import the Calendar component 
 * Re-add the Calendar component to the form and paste back in your parameters.

I'll post this on the MS community board but since all this stuff is still in preview they will probably just say tough luck.
