### ISSUE TITLE
Possible to enable search and filters in a subgrid

### ISSUE THREAD

**Issue by zidhjian** [rwilson504/PCFControls#92]
Hello, would it be a hard task to enable the search and filter options when this control is used in a subgrid?

**Comment by rwilson504** [comment]
@zidhjian which one of the components would you like to see that on?

**Comment by zidhjian** [comment]
> @zidhjian which one of the components would you like to see that on?

The Details List component. Another thing I noticed was that you are not able to scroll sideways only upright. Which makes it hard for lists that have many columns. Thanks a lot! 😊

**Comment by rwilson504** [comment]
Scrolling:
In the standard UCI grid the columns widths are set.  It should be possible to set those widths instead of just distributing all the widths the way i have been.  I would probably make this a property of the component so the customizer can determine which way they would like them to display when setting up the view.

Quick Find:
I had turned off the quick find because of the way in which quick find works.  I always hated that it takes you to the quick find view instead of staying on your current view.  Now that there is an option to this off and stay on the same view after doing a quick find it's probably a good time to turn this back on for the component.
[Turn Off Quick Find View Change](https://stoneridgesoftware.com/improved-search-functionality-dynamics-365-customer-engagement/)

Filters:
This would be a lot harder.  I would have to build all the filtering into my control which right now I don't really have the time to do.

**Comment by zidhjian** [comment]
Hello Rick,

Thank you very much for the information!
I will try to set the quick-search option as you guided.

Would you consider modifying the component filtering for a charge? The company I represent would find a great use of it if had the filters.

Ystävällisin Terveisin
Marcus
________________________________
